services:
  keycloak:
    # image: quay.io/keycloak/keycloak:25.0.6
    build:
      # ? Custom Dockerfile
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # command: >
    #   start-dev
    #   --spi-theme-static-max-age=-1
    #   --spi-theme-cache-themes=false
    #   --spi-theme-cache-templates=false
    volumes:
      # ? Keycloak data
      - keycloak_data:/opt/keycloak/data
      # ? Custom keycloak themes
      - ./themes:/opt/keycloak/themes
      # ? Keycloak interceptor
      - ./keycloak-custom-extension.jar:/opt/keycloak/providers/keycloak-custom-extension.jar
    restart: unless-stopped

volumes:
  keycloak_data:
